#!/usr/bin/env python3
"""Generate KBStream's launcher branding: the Google TV banner, the app icons
and the logo lockup.

Why this exists instead of a hand-made PNG in res/: this container has no image
library and no SVG renderer, and the launcher assets have to be bitmaps --
a TV launcher rasters the banner itself, and `mipmap-anydpi-v26` alone leaves
every API 23-25 box (Fire OS 5/6, older Google TV sticks) with no icon asset at
all. So the artwork is defined ONCE here, as polygons plus gradients, in design
units, and then:

  * rasterized to PNG (analytic coverage across x, N sub-scanlines down y),
  * serialized to SVG for the repo/website,
  * serialized to vector-drawable XML for the adaptive icon's layers.

Everything is regenerated by running this file; there is no artwork to hand-edit.

The mark is the brass play button -- the ringed glyph a viewer already reads as
"watch something" -- defined once in the MARK_* constants and reused by the
icon, the banner, the lockup and the notification silhouette, so every surface
carries the same drawing. The wordmark is set in the app's own oswald_bold.ttf
through font_glyphs.py, so the letterforms are a designed typeface rather than
traced shapes, and the palette is the app's theme (void navy + the single brass
accent).

Usage:
    render_brand_assets.py                 # write every asset
    render_brand_assets.py --preview NAME  # rasterize one piece as ASCII
"""

import math
import os
import struct
import sys
import zlib
from array import array

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from font_glyphs import Font  # noqa: E402  (bundled-Oswald outline reader)

RES = os.path.join(ROOT, "app", "src", "main", "res")
BRAND = os.path.join(ROOT, "docs", "brand")

BOLD = Font(os.path.join(RES, "font", "oswald_bold.ttf"))
MEDIUM = Font(os.path.join(RES, "font", "oswald_medium.ttf"))

# Sub-scanlines per pixel row. x coverage is analytic, so this only governs how
# finely near-horizontal edges are graded.
SS = 6


# --------------------------------------------------------------------------- #
# palette (mirrors ui/theme/Theme.kt + res/values/colors.xml)
# --------------------------------------------------------------------------- #

def rgb(spec, alpha=1.0):
    h = spec.lstrip("#")
    return (
        int(h[0:2], 16) / 255.0,
        int(h[2:4], 16) / 255.0,
        int(h[4:6], 16) / 255.0,
        alpha,
    )


TILE_TOP = rgb("1D2838")
TILE_BOT = rgb("080B11")
BANNER_TOP = rgb("1B2434")
BANNER_BOT = rgb("090C12")
BRASS_HI = rgb("F7CE86")
BRASS_LO = rgb("CE872A")
BRASS = rgb("E8A33D")
TEXT_HI = rgb("F3EFE4")
TEXT_LO = rgb("8891A0")


# --------------------------------------------------------------------------- #
# paints: "solid" | "lin" (p0, p1, c0, c1) | "rad" (centre, r, colour, a, gamma)
# --------------------------------------------------------------------------- #

def with_alpha(c, a):
    """The same colour at a fraction of its alpha. The plate is drawn at full
    strength for the opaque outputs and faded for the translucent banner."""
    return (c[0], c[1], c[2], c[3] * a)


def solid(c):
    return ("solid", c)


def lin(p0, p1, c0, c1):
    return ("lin", p0, p1, c0, c1)


def rad(centre, r, colour, alpha, gamma=1.7):
    return ("rad", centre, r, colour, alpha, gamma)


def paint_at(p, x, y):
    kind = p[0]
    if kind == "solid":
        return p[1]
    if kind == "lin":
        (x0, y0), (x1, y1), c0, c1 = p[1], p[2], p[3], p[4]
        dx, dy = x1 - x0, y1 - y0
        den = dx * dx + dy * dy
        t = 0.0 if den == 0 else ((x - x0) * dx + (y - y0) * dy) / den
        t = 0.0 if t < 0 else (1.0 if t > 1 else t)
        return (
            c0[0] + (c1[0] - c0[0]) * t,
            c0[1] + (c1[1] - c0[1]) * t,
            c0[2] + (c1[2] - c0[2]) * t,
            c0[3] + (c1[3] - c0[3]) * t,
        )
    # radial: bright at the centre, fading to nothing at r
    (cx, cy), r, c, a, gamma = p[1], p[2], p[3], p[4], p[5]
    dx, dy = x - cx, y - cy
    d2 = dx * dx + dy * dy
    if d2 >= r * r:
        return (c[0], c[1], c[2], 0.0)
    t = 1.0 - math.sqrt(d2) / r
    return (c[0], c[1], c[2], a * t ** gamma)


def constant_in_x(p):
    """True when a paint only varies down the y axis (lets fill() hoist it)."""
    if p[0] == "solid":
        return True
    if p[0] == "lin":
        return abs(p[1][0] - p[2][0]) < 1e-9
    return False


def xf_paint(p, k, dx, dy):
    if p[0] == "lin":
        (x0, y0), (x1, y1) = p[1], p[2]
        return ("lin", (x0 * k + dx, y0 * k + dy), (x1 * k + dx, y1 * k + dy), p[3], p[4])
    if p[0] == "rad":
        (cx, cy) = p[1]
        return ("rad", (cx * k + dx, cy * k + dy), p[2] * k, p[3], p[4], p[5])
    return p


# --------------------------------------------------------------------------- #
# geometry: every shape is a closed polyline (curves are flattened with enough
# segments that the facets stay well under a quarter pixel)
# --------------------------------------------------------------------------- #

def _dist(a, b):
    return math.hypot(b[0] - a[0], b[1] - a[1])


def rounded_polygon(pts, r):
    """Fillet every corner of a convex polygon to radius r."""
    n = len(pts)
    out = []
    for i in range(n):
        prev, cur, nxt = pts[i - 1], pts[i], pts[(i + 1) % n]
        if r <= 1e-9:
            out.append(cur)
            continue
        d1, d2 = _dist(cur, prev), _dist(cur, nxt)
        if d1 < 1e-9 or d2 < 1e-9:
            out.append(cur)
            continue
        v1 = ((prev[0] - cur[0]) / d1, (prev[1] - cur[1]) / d1)
        v2 = ((nxt[0] - cur[0]) / d2, (nxt[1] - cur[1]) / d2)
        cos_t = max(-1.0, min(1.0, v1[0] * v2[0] + v1[1] * v2[1]))
        theta = math.acos(cos_t)
        if theta < 1e-6 or abs(math.pi - theta) < 1e-6:
            out.append(cur)
            continue
        # Tangent points sit r/tan(theta/2) back from the vertex; that is the
        # real fillet of radius r, not a fixed distance along each edge.
        back = r / math.tan(theta / 2.0)
        back = min(back, d1 / 2.0, d2 / 2.0)
        eff = back * math.tan(theta / 2.0)
        t1 = (cur[0] + v1[0] * back, cur[1] + v1[1] * back)
        t2 = (cur[0] + v2[0] * back, cur[1] + v2[1] * back)
        a0 = math.atan2(t1[1] - cur[1], t1[0] - cur[0])
        a1 = math.atan2(t2[1] - cur[1], t2[0] - cur[0])
        d = a1 - a0
        while d > math.pi:
            d -= 2 * math.pi
        while d < -math.pi:
            d += 2 * math.pi
        steps = max(3, int(round(20 * abs(d) / (math.pi / 2))))
        out.extend(
            (
                cur[0] + eff * math.cos(a0 + d * s / steps),
                cur[1] + eff * math.sin(a0 + d * s / steps),
            )
            for s in range(steps + 1)
        )
    return out


def rect(x, y, w, h, r=0.0):
    pts = [(x, y), (x + w, y), (x + w, y + h), (x, y + h)]
    return rounded_polygon(pts, r)


def circle(cx, cy, r, steps=180):
    return [
        (cx + r * math.cos(2 * math.pi * i / steps), cy + r * math.sin(2 * math.pi * i / steps))
        for i in range(steps)
    ]


def reverse(poly):
    return poly[::-1]


def ring(x, y, w, h, r, thickness):
    """A filleted outline: outer contour plus the inner one wound the other way,
    so the nonzero fill leaves the middle empty."""
    inner = rect(x + thickness, y + thickness, w - 2 * thickness, h - 2 * thickness,
                 max(0.0, r - thickness))
    return [rect(x, y, w, h, r), reverse(inner)]


def annulus(cx, cy, r_out, r_in, steps=240):
    """The same trick as ring(), for a circular bezel."""
    return [circle(cx, cy, r_out, steps), reverse(circle(cx, cy, r_in, steps))]


def bbox(polys):
    xs = [p[0] for poly in polys for p in poly]
    ys = [p[1] for poly in polys for p in poly]
    return min(xs), min(ys), max(xs), max(ys)


def move(polys, dx, dy):
    return [[(x + dx, y + dy) for x, y in poly] for poly in polys]


def xf(polys, k, dx=0.0, dy=0.0):
    return [[(x * k + dx, y * k + dy) for x, y in poly] for poly in polys]


def scale_layers(layers, k, dx=0.0, dy=0.0):
    return [
        (xf(polys, k, dx, dy), xf_paint(paint, k, dx, dy))
        for polys, paint in layers
    ]


# --------------------------------------------------------------------------- #
# type: wordmarks set from the app's own Oswald outlines
# --------------------------------------------------------------------------- #

def _quad(p0, p1, p2, steps=10):
    out = []
    for i in range(1, steps + 1):
        t = i / steps
        u = 1 - t
        out.append(
            (
                u * u * p0[0] + 2 * u * t * p1[0] + t * t * p2[0],
                u * u * p0[1] + 2 * u * t * p1[1] + t * t * p2[1],
            )
        )
    return out


def _contour_poly(contour, steps=10):
    pts = list(contour)
    if not pts[0][2]:
        if not pts[-1][2]:
            pts = [((pts[0][0] + pts[-1][0]) / 2.0, (pts[0][1] + pts[-1][1]) / 2.0, True)] + pts
        else:
            pts = [pts[-1]] + pts[:-1]
    out = [(pts[0][0], pts[0][1])]
    i, n = 1, len(pts)
    while i <= n:
        p = pts[i % n]
        if p[2]:
            out.append((p[0], p[1]))
            i += 1
        else:
            q = pts[(i + 1) % n]
            out += _quad(out[-1], (p[0], p[1]), (q[0], q[1]), steps)
            i += 2
    return out


def wordmark(font, text, cap, tracking_em=0.0, x=0.0, y=0.0):
    """Set `text` in caps with an ink height of `cap`, top-left of the ink at
    (x, y). Returns closed polylines, y-down like the rest of the design."""
    missing = [ch for ch in text if font.gid(ch) == 0]
    if missing:
        raise ValueError("%r is not in the font" % "".join(missing))
    glyphs = []
    pen = 0.0
    for ch in text:
        gid = font.gid(ch)
        contours = [_contour_poly(c) for c in font.contours(gid)]
        glyphs.append((contours, pen))
        pen += font.advance(gid) + font.upem * tracking_em
    xs = [p[0] for polys, _ in glyphs for poly in polys for p in poly]
    ys = [p[1] for polys, _ in glyphs for poly in polys for p in poly]
    s = cap / (max(ys) - min(ys))
    tx = x - min(xs) * s
    ty = y + max(ys) * s
    return [
        [((p[0] + off) * s + tx, ty - p[1] * s) for p in poly]
        for polys, off in glyphs
        for poly in polys
    ]


def fitted_line(font, text, cap, target_w, max_tracking=0.34):
    """Set a secondary line so its ink measures exactly `target_w` by solving
    its tracking. Both lines of a lockup then share a measure, which is what
    makes a two-line lockup read as set rather than as stacked text."""
    base = wordmark(font, text, cap, 0.0)
    probe = wordmark(font, text, cap, 0.10)
    w0 = bbox(base)[2] - bbox(base)[0]
    slope = ((bbox(probe)[2] - bbox(probe)[0]) - w0) / 0.10
    if slope <= 1e-6:
        return base
    t = (target_w - w0) / slope
    return wordmark(font, text, cap, max(0.02, min(max_tracking, t)))


# --------------------------------------------------------------------------- #
# rasterizer: painter's algorithm into one straight-alpha float buffer
# --------------------------------------------------------------------------- #

def new_buffer(w, h):
    return array("f", b"\0" * (16 * w * h))


def _check(polys):
    """Catch a bare polyline where a list of them was meant: fill() would
    otherwise iterate its points and quietly draw an empty layer."""
    for poly in polys:
        if len(poly) < 3 or not isinstance(poly[0], (tuple, list)) or len(poly[0]) != 2:
            raise ValueError("shape is not a list of polylines: %r" % (poly,))


def _edges(polys):
    out = []
    for poly in polys:
        if len(poly) < 3:
            continue
        prev = poly[-1]
        for cur in poly:
            if prev[1] != cur[1]:
                out.append((prev[0], prev[1], cur[0], cur[1], 1 if cur[1] > prev[1] else -1))
            prev = cur
    return out


def fill(buf, w, h, polys, paint, ss=SS):
    """Fill closed polylines into the buffer with the nonzero rule.

    Coverage is exact across x and sampled on `ss` sub-scanlines down y, which
    is what keeps the long, near-horizontal edges of the play triangle and the
    type clean without supersampling the whole canvas.
    """
    _check(polys)
    es = _edges(polys)
    if not es:
        return
    y_lo = max(0, int(math.floor(min(min(e[1], e[3]) for e in es))))
    y_hi = min(h, int(math.ceil(max(max(e[1], e[3]) for e in es))))
    flat = constant_in_x(paint)
    for sub in range(y_lo * ss, y_hi * ss):
        yc = (sub + 0.5) / ss
        cross = []
        for ax, ay, bx, by, d in es:
            if (ay <= yc < by) or (by <= yc < ay):
                cross.append((ax + (yc - ay) / (by - ay) * (bx - ax), d))
        if len(cross) < 2:
            continue
        cross.sort()
        spans = []
        wind = 0
        start = None
        for xc, d in cross:
            if wind == 0:
                start = xc
            wind += d
            if wind == 0 and start is not None:
                if xc > start:
                    spans.append((start, xc))
                start = None
        if not spans:
            continue
        row = (sub // ss) * w
        fixed = paint_at(paint, 0.0, yc) if flat else None
        inv = 1.0 / ss
        for a, b in spans:
            gx0 = max(0, int(math.floor(a)))
            gx1 = min(w, int(math.ceil(b)))
            for gx in range(gx0, gx1):
                cov = min(b, gx + 1.0) - max(a, float(gx))
                if cov <= 0:
                    continue
                c = fixed if fixed is not None else paint_at(paint, gx + 0.5, yc)
                sa = cov * inv * c[3]
                if sa <= 0.0:
                    continue
                if sa > 1.0:
                    sa = 1.0
                i = (row + gx) * 4
                da = buf[i + 3]
                oa = sa + da * (1.0 - sa)
                if oa <= 0.0:
                    continue
                wd = da * (1.0 - sa)
                buf[i] = (c[0] * sa + buf[i] * wd) / oa
                buf[i + 1] = (c[1] * sa + buf[i + 1] * wd) / oa
                buf[i + 2] = (c[2] * sa + buf[i + 2] * wd) / oa
                buf[i + 3] = oa


def render(layers, w, h, ss=SS):
    buf = new_buffer(w, h)
    for polys, paint in layers:
        fill(buf, w, h, polys, paint, ss)
    return buf


def blit(dst, dw, dh, src, sw, sh, ox, oy):
    """src-over one rendered buffer onto another (used for the review sheet)."""
    for y in range(sh):
        ty = y + oy
        if ty < 0 or ty >= dh:
            continue
        srow = y * sw * 4
        drow = ty * dw * 4
        for x in range(sw):
            tx = x + ox
            if tx < 0 or tx >= dw:
                continue
            si = srow + x * 4
            sa = src[si + 3]
            if sa <= 0.0:
                continue
            di = drow + tx * 4
            if sa >= 1.0:
                dst[di] = src[si]
                dst[di + 1] = src[si + 1]
                dst[di + 2] = src[si + 2]
                dst[di + 3] = 1.0
                continue
            da = dst[di + 3]
            oa = sa + da * (1.0 - sa)
            wd = da * (1.0 - sa)
            dst[di] = (src[si] * sa + dst[di] * wd) / oa
            dst[di + 1] = (src[si + 1] * sa + dst[di + 1] * wd) / oa
            dst[di + 2] = (src[si + 2] * sa + dst[di + 2] * wd) / oa
            dst[di + 3] = oa


# --------------------------------------------------------------------------- #
# encoders: PNG (stdlib zlib), SVG, Android vector drawable
# --------------------------------------------------------------------------- #

def _png_chunk(tag, data):
    return (
        struct.pack(">I", len(data))
        + tag
        + data
        + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    )


def png_bytes(buf, w, h, alpha=True):
    lanes = 4 if alpha else 3
    vals = bytes(min(255, max(0, int(v * 255.0 + 0.5))) for v in buf)
    if alpha:
        body = vals
    else:
        body = bytearray(w * h * lanes)
        body[0::3] = vals[0::4]
        body[1::3] = vals[1::4]
        body[2::3] = vals[2::4]
        body = bytes(body)
    stride = w * lanes
    raw = bytearray()
    for y in range(h):
        raw.append(0)
        raw += body[y * stride:(y + 1) * stride]
    ihdr = struct.pack(">IIBBBBB", w, h, 8, 6 if alpha else 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", ihdr)
        + _png_chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + _png_chunk(b"IEND", b"")
    )


def _hexc(c):
    return "%02X%02X%02X" % (
        min(255, max(0, int(c[0] * 255 + 0.5))),
        min(255, max(0, int(c[1] * 255 + 0.5))),
        min(255, max(0, int(c[2] * 255 + 0.5))),
    )


def _argb(c):
    """#AARRGGBB, the form Android's resources want."""
    return "#%02X%s" % (min(255, max(0, int(c[3] * 255 + 0.5))), _hexc(c))


def _poly_d(polys, prec=2):
    fmt = "%%.%df %%.%df " % (prec, prec)
    out = []
    for poly in polys:
        if len(poly) < 3:
            continue
        out.append("M")
        out.append("".join(fmt % p for p in poly) + "Z")
    return " ".join(out)


def svg_doc(layers, w, h, title):
    defs = []
    body = []
    n = 0
    for polys, paint in layers:
        if paint[0] == "solid":
            fill = _hexc(paint[1])
            extra = "" if paint[1][3] >= 1.0 else ' fill-opacity="%.3f"' % paint[1][3]
        else:
            n += 1
            gid = "g%d" % n
            if paint[0] == "lin":
                (x0, y0), (x1, y1), c0, c1 = paint[1], paint[2], paint[3], paint[4]
                defs.append(
                    '<linearGradient id="%s" gradientUnits="userSpaceOnUse" x1="%.2f" y1="%.2f" '
                    'x2="%.2f" y2="%.2f"><stop offset="0" stop-color="#%s" stop-opacity="%.3f"/>'
                    '<stop offset="1" stop-color="#%s" stop-opacity="%.3f"/></linearGradient>'
                    % (gid, x0, y0, x1, y1, _hexc(c0), c0[3], _hexc(c1), c1[3])
                )
            else:
                (cx, cy), r, c, a, gamma = paint[1], paint[2], paint[3], paint[4], paint[5]
                stops = "".join(
                    '<stop offset="%.2f" stop-color="#%s" stop-opacity="%.3f"/>'
                    % (t, _hexc(c), a * (1.0 - t) ** gamma)
                    for t in (0.0, 0.25, 0.5, 0.75, 1.0)
                )
                defs.append(
                    '<radialGradient id="%s" gradientUnits="userSpaceOnUse" cx="%.2f" cy="%.2f" '
                    'r="%.2f">%s</radialGradient>' % (gid, cx, cy, r, stops)
                )
            fill = "url(#%s)" % gid
            extra = ""
        body.append('<path d="%s" fill="%s"%s/>' % (_poly_d(polys), fill, extra))
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<svg xmlns="http://www.w3.org/2000/svg" width="%g" height="%g" viewBox="0 0 %g %g" '
        'role="img" aria-label="%s">\n<title>%s</title>\n<defs>%s</defs>\n%s\n</svg>\n'
        % (w, h, w, h, title, title, "".join(defs), "\n".join(body))
    )


def vector_xml(size, w, h, shapes, desc):
    """shapes: [(path_d, paint)] -- paint is a solid RGBA, a linear gradient or a
    radial one. A gradient paint is written as an <aapt:attr> inline colour, so
    the layer stays a plain vector drawable to every API level that can read
    one. Android's <gradient> takes two colours and no falloff exponent, so a
    radial paints its centre colour to fully transparent and the softness comes
    from the alpha pair (the raster and the SVG keep the exact curve)."""
    body = []
    for d, paint in shapes:
        if paint[0] == "solid":
            body.append(
                '    <path\n        android:fillColor="%s"\n        android:pathData="%s" />'
                % (_argb(paint[1]), d)
            )
            continue
        if paint[0] == "lin":
            (x0, y0), (x1, y1), c0, c1 = paint[1], paint[2], paint[3], paint[4]
            gradient = (
                '                android:type="linear"\n'
                '                android:startX="%.2f"\n                android:startY="%.2f"\n'
                '                android:endX="%.2f"\n                android:endY="%.2f"\n'
                '                android:startColor="%s"\n'
                '                android:endColor="%s" />\n'
                % (x0, y0, x1, y1, _argb(c0), _argb(c1))
            )
        else:
            (cx, cy), r, c, a = paint[1], paint[2], paint[3], paint[4]
            gradient = (
                '                android:type="radial"\n'
                '                android:centerX="%.2f"\n                android:centerY="%.2f"\n'
                '                android:gradientRadius="%.2f"\n'
                '                android:startColor="%s"\n'
                '                android:endColor="%s" />\n'
                % (cx, cy, r, _argb((c[0], c[1], c[2], a)), _argb((c[0], c[1], c[2], 0.0)))
            )
        body.append(
            '    <path android:pathData="%s">\n'
            '        <aapt:attr name="android:fillColor">\n'
            '            <gradient\n%s'
            '        </aapt:attr>\n'
            '    </path>' % (d, gradient)
        )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- %s -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    xmlns:aapt="http://schemas.android.com/aapt"\n'
        '    android:width="%gdp"\n    android:height="%gdp"\n'
        '    android:viewportWidth="%g"\n    android:viewportHeight="%g">\n%s\n</vector>\n'
        % (desc, size, size, w, h, "\n".join(body))
    )


def write(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    mode = "wb" if isinstance(data, (bytes, bytearray)) else "w"
    with open(path, mode) as fh:
        fh.write(data)
    return os.path.relpath(path, ROOT)


# --------------------------------------------------------------------------- #
# the mark: a brass play button -- a bezelled ring with the play triangle set
# into it, which is the shape a viewer already reads as "watch something"
# before they read a single letter. The brand sits in the material rather than
# in an abstract monogram: the app's brass, lit from above, on a glass face.
# --------------------------------------------------------------------------- #

MARK_RING = 0.070       # bezel thickness, as a fraction of the button's diameter
MARK_FACE = 0.11        # alpha of the glass face inside the bezel
MARK_TRI_H = 0.52       # triangle height, as a fraction of the diameter
MARK_TRI_ASPECT = 0.88  # width / height; a play glyph is taller than it is wide
MARK_FILLET = 0.085     # triangle corner fillet, as a fraction of its height
MARK_NUDGE = 0.020      # optical centring: a triangle's mass sits left of its box
MARK_D = 58.0           # the button's diameter in every lockup, so the mark-to-
                        # wordmark ratio is the same on the banner and the logo


def mark(d, x=0.0, y=0.0):
    """The button as one path: the bezel (an annulus is two contours, so it
    fills as a ring under the nonzero rule) plus the play glyph inside it.
    `d` is the button's diameter; (x, y) is the top-left of its bounding box."""
    bezel, tri = mark_split(d, x, y)
    return bezel + tri


def mark_split(d, x=0.0, y=0.0):
    """The same geometry as two pieces -- (bezel polys, glyph polys) -- so each
    can take its own fill. The glyph is nudged right of the geometric centre:
    a triangle's mass sits to the left of its bounding box, and centring the box
    is what leaves a play mark looking off-centre."""
    cx, cy = x + d / 2.0, y + d / 2.0
    r_in = d / 2.0 * (1.0 - 2.0 * MARK_RING)
    tri_h = MARK_TRI_H * d
    tri_w = tri_h * MARK_TRI_ASPECT
    tx = cx - tri_w / 2.0 + MARK_NUDGE * d
    ty = cy - tri_h / 2.0
    return (
        annulus(cx, cy, d / 2.0, r_in),
        [rounded_polygon(
            [(tx, ty), (tx + tri_w, cy), (tx, ty + tri_h)], MARK_FILLET * tri_h
        )],
    )


def mark_layers(d, x, y):
    """The mark alone, lit from above (the theme's projector-bulb warmth): the
    glass face first, then the bezel, then the brightest piece, the glyph."""
    cx, cy = x + d / 2.0, y + d / 2.0
    bezel, tri = mark_split(d, x, y)
    return [
        ([circle(cx, cy, d / 2.0 * (1.0 - 2.0 * MARK_RING))],
         rad((cx, cy - 0.06 * d), 0.62 * d, BRASS, MARK_FACE)),
        (bezel, lin((0.0, y), (0.0, y + d), BRASS, BRASS_LO)),
        (tri, lin((0.0, y), (0.0, y + d), BRASS_HI, BRASS)),
    ]


# --------------------------------------------------------------------------- #
# the tile: the app icon's plate
# --------------------------------------------------------------------------- #

TILE = 108.0

# The mark inside the icon plate. The adaptive-icon safe zone is a 66dp
# diameter circle centred in the 108dp layer -- a launcher is free to crop
# everything outside it -- so 62 leaves 2dp of margin all round. It used to be
# 58, which read as a small badge floating in the plate rather than as the
# app's mark: the launcher rail draws this at 48-96px, and 58/108 of 48px is
# under 26px of button.
ICON_MARK_D = 62.0


def tile_plate(inset=3.5, round_corner=False):
    if round_corner:
        return circle(TILE / 2.0, TILE / 2.0, TILE / 2.0 - inset)
    side = TILE - 2 * inset
    return rect(inset, inset, side, side, side * 0.225)


def icon_layers(round_icon=False):
    layers = [
        ([tile_plate(round_corner=round_icon)], lin((0.0, 0.0), (0.0, TILE), TILE_TOP, TILE_BOT)),
        ([circle(TILE / 2.0, TILE / 2.0, 52.0)], rad((TILE / 2.0, TILE / 2.0 - 4), 52.0, BRASS, 0.17)),
        (ring(5.6, 5.6, TILE - 11.2, TILE - 11.2, (TILE - 11.2) * 0.21, 1.5), solid(rgb("E8A33D", 0.30))),
    ]
    d = ICON_MARK_D
    layers += mark_layers(d, (TILE - d) / 2.0, (TILE - d) / 2.0)
    return layers


# --------------------------------------------------------------------------- #
# the TV banner (design units = 320x180, the spec's own numbers)
# --------------------------------------------------------------------------- #

BANNER_W = 320.0
BANNER_H = 180.0

TAGLINE = "MOVIES \u00b7 SERIES \u00b7 LIVE TV"

# The plate is authored once, in design units measured at the banner's own
# 320x180 basis, and `k` scales it: 1.0 is the Leanback banner exactly, 4.0 is
# the same artwork at 1280x720. The store listing plates reuse this composition
# rather than restating it, so the project has one lockup instead of three that
# drift apart.
PLATE_WORD_CAP = 29.0
PLATE_TAG_CAP = 7.5
PLATE_LEAD = 11.0       # wordmark block down to the tagline
PLATE_MARK_GAP = 26.0   # mark across to the wordmark
PLATE_HALO_R = 132.0
PLATE_BEAM_H = 78.0     # half-height of the light beam at the plate's right edge

# The launcher banner's safe area, and why it needs one. A TV launcher does not
# draw the banner bare: it puts it inside its own card, with rounded corners,
# and scales that card up while the tile holds focus. Artwork running flush to
# the edge of the 320x180 therefore has its corners cut off by that rounding,
# and reads as oversized beside the launchers' own banners, which are
# transparent lockups floating in the middle of the slot. So the plate is
# pulled in from the edge (the margin stays transparent, so any rounding crops
# empty space instead of artwork), faded so the wallpaper reads through it, and
# its lockup drops a notch.
PLATE_INSET = 14.0
PLATE_RADIUS = 13.0
PLATE_ALPHA = 0.78
PLATE_LOCK = 0.90


def plate_layers(w, h, k=1.0, inset=0.0, alpha=1.0, lock=1.0):
    """The KBStream plate: background, mark-as-light-source, lockup.

    The lockup is centred in (w, h) at design scale `k`, so a wider plate gets
    more breathing room around the same lockup rather than a stretched one.
    `k = 1.0` at 320x180 is the TV banner, bit for bit.

    `inset` pulls the plate in from the canvas edge and leaves that margin
    transparent, `alpha` fades the plate so the wallpaper reads through it, and
    `lock` scales the lockup inside it. All three default to the store plates'
    full-bleed, opaque, full-size form -- see PLATE_INSET for why the launcher
    banner does not use those defaults.
    """
    scale = k * lock
    mark_d = MARK_D * scale
    word = wordmark(BOLD, "KBSTREAM", cap=PLATE_WORD_CAP * scale, tracking_em=0.05)
    word_w = bbox(word)[2] - bbox(word)[0]
    tag = fitted_line(MEDIUM, TAGLINE, cap=PLATE_TAG_CAP * scale, target_w=word_w)
    gap = PLATE_MARK_GAP * scale
    total = mark_d + gap + word_w
    x0 = (w - total) / 2.0
    mark_x = x0
    mark_y = (h - mark_d) / 2.0
    text_x = x0 + mark_d + gap
    block_top = (h - (PLATE_WORD_CAP + PLATE_LEAD + PLATE_TAG_CAP) * scale) / 2.0

    # The mark is the plate's light source: a halo sits behind it and a wide,
    # very faint beam opens out of the play glyph across the lockup. Both are
    # low enough that they read as depth rather than as decoration -- a plain
    # navy plate with a logo dropped on it is what looks cheap.
    tip_x, tip_y = mark_x + mark_d, h / 2.0
    beam_h = PLATE_BEAM_H * scale
    halo_r = PLATE_HALO_R * scale
    # The plate's own edge: the halo and the beam stop here rather than at the
    # canvas, because with the margin transparent the halo would otherwise
    # strand a warm glow out past the card.
    ix = inset * k
    edge = w - ix
    if inset > 0:
        glow_x = tip_x - mark_d / 2.0
        halo_r = min(halo_r, glow_x - ix, edge - glow_x, (h - 2 * ix) / 2.0)
    layers = [
        ([rect(ix, ix, w - 2 * ix, h - 2 * ix, PLATE_RADIUS * k if inset > 0 else 0.0)],
         lin((0.0, ix), (0.0, h - ix),
             with_alpha(BANNER_TOP, alpha), with_alpha(BANNER_BOT, alpha))),
        ([[(tip_x, tip_y), (edge, tip_y - beam_h), (edge, tip_y + beam_h)]],
         lin((tip_x, tip_y), (edge * 0.86, tip_y), rgb("F7CE86", 0.11), rgb("F7CE86", 0.0))),
        ([circle(tip_x - mark_d / 2.0, tip_y, halo_r)],
         rad((tip_x - mark_d / 2.0, tip_y - 6.0 * scale), halo_r, BRASS, 0.16)),
    ]
    layers += mark_layers(mark_d, mark_x, mark_y)
    layers.append((move(word, text_x, block_top), solid(TEXT_HI)))
    layers.append((move(tag, text_x, block_top + (PLATE_WORD_CAP + PLATE_LEAD) * scale),
                   solid(rgb("8891A0", 0.92))))
    return layers


# The launcher banner in its two forms. The translucent one is the default,
# and inset/alpha/lock are what let it survive the launcher's own card.
BANNER_TRANSLUCENT = dict(inset=PLATE_INSET, alpha=PLATE_ALPHA, lock=PLATE_LOCK)
BANNER_SOLID = dict(inset=PLATE_INSET, alpha=1.0, lock=PLATE_LOCK)


def banner_layers(solid=False):
    return plate_layers(
        BANNER_W, BANNER_H, **(BANNER_SOLID if solid else BANNER_TRANSLUCENT)
    )


# The bare lockup's size. The plate's own lockup is scaled down by PLATE_LOCK
# to breathe inside the plate; a bare lockup is not inside anything, so it runs
# at full size (the same numbers the store plates and the icon mark use).
BANNER_LOCKUP_LOCK = 1.0


def banner_lockup_layers(lock=BANNER_LOCKUP_LOCK):
    """The banner's lockup alone, on a fully transparent field.

    The same geometry as the plate's own lockup -- one lockup, so the mark and
    the wordmark cannot drift apart between the two forms -- minus everything
    that is not the brand: no plate, no halo, no beam and no tagline. What is
    left in the PNG is the brass play button and the word KBSTREAM, so a
    launcher that draws its own card (or its own colour behind the tile) gets
    nothing but the brand painted over it.

    The wordmark is centred by its CAP height rather than inside the plate's
    three-line block: with the tagline gone there is no second line to balance
    against, and centring that block would sit the word high.
    """
    scale = lock
    mark_d = MARK_D * scale
    word = wordmark(BOLD, "KBSTREAM", cap=PLATE_WORD_CAP * scale, tracking_em=0.05)
    word_w = bbox(word)[2] - bbox(word)[0]
    gap = PLATE_MARK_GAP * scale
    total = mark_d + gap + word_w
    x0 = (BANNER_W - total) / 2.0
    mark_y = (BANNER_H - mark_d) / 2.0
    text_x = x0 + mark_d + gap
    text_y = (BANNER_H - PLATE_WORD_CAP * scale) / 2.0
    layers = mark_layers(mark_d, x0, mark_y)
    layers.append((move(word, text_x, text_y), solid(TEXT_HI)))
    return layers


# --------------------------------------------------------------------------- #
# the logo lockup (transparent, for the README / website / anywhere vector)
# --------------------------------------------------------------------------- #

LOGO_W = 300.0
LOGO_H = 96.0


def logo_layers():
    mark_d = MARK_D
    word = wordmark(BOLD, "KBSTREAM", cap=29.0, tracking_em=0.05)
    word_w = bbox(word)[2] - bbox(word)[0]
    tag = fitted_line(MEDIUM, TAGLINE, cap=8.0, target_w=word_w)
    gap = 24.0
    total = mark_d + gap + word_w
    x0 = (LOGO_W - total) / 2.0
    mark_y = (LOGO_H - mark_d) / 2.0
    text_x = x0 + mark_d + gap
    block_top = (LOGO_H - (29.0 + 12.0 + 8.0)) / 2.0
    layers = mark_layers(mark_d, x0, mark_y)
    layers.append((move(word, text_x, block_top), solid(TEXT_HI)))
    layers.append((move(tag, text_x, block_top + 29.0 + 12.0), solid(TEXT_LO)))
    return layers


# --------------------------------------------------------------------------- #
# outputs
# --------------------------------------------------------------------------- #

ICON_SIZES = [("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)]

# The two listing plates. A Play listing wants a 1280x720 banner and a 1024x500
# feature graphic, and neither is the launcher banner resampled: they are the
# same composition laid out at their own size, so the type and the mark keep
# their proportions. The feature graphic is laid out at 1024 wide (k = 1024/320)
# which is what holds its lockup at the same relative size as the banner's.
STORE_PLATES = (
    ("kbstream-banner-1280x720", 1280.0, 720.0, 4.0),
    ("kbstream-feature-graphic-1024x500", 1024.0, 500.0, 3.2),
)


def emit_banner():
    # The design is authored at the spec's own 320x180; the bitmap is written at
    # 2x (xhdpi) for a TV launcher's overscan, so the layers have to be scaled
    # with it -- rendering the design into a 640x360 buffer would paint only the
    # top-left quarter.
    #
    # tv_banner -- what android:banner points at -- is the ORIGINAL full-bleed
    # opaque plate (plate_layers' design defaults: no inset, opaque, full-size
    # lockup). The inset/translucent variants that were tried as the launcher
    # card are still emitted beside it, so switching between them stays a
    # drawable reference rather than a regeneration.
    #
    # The lockup-only form is the exception: it is a DOWNLOAD for surfaces
    # outside the app, so it is written to BRAND and deliberately never to
    # res/ (see the forms tuple).
    written = []
    forms = (
        # (drawable, brand suffix, title suffix, layers, needs-alpha-channel,
        #  ships-in-the-apk)
        # The full-bleed form is opaque edge to edge, so it is written as RGB
        # exactly as it was before the inset/translucent experiment; the inset
        # forms need a real alpha channel (an RGB PNG has nowhere to put the
        # transparent margin and would come out black).
        ("tv_banner", "", "", plate_layers(BANNER_W, BANNER_H), False, True),
        ("tv_banner_plate", "-plate", " (solid plate)",
         banner_layers(solid=True), True, True),
        ("tv_banner_translucent", "-translucent", " (translucent)",
         banner_layers(solid=False), True, True),
        # Lockup only: mark + wordmark on a transparent field, no plate at all.
        # NOT a launcher card. android:banner is drawn AS the card artwork, so
        # a 320x180 strip carrying nothing but the lockup is for a website, a
        # listing, or anywhere the brand has to sit on someone else's
        # background -- and shipping it in res/ would only add an unreferenced
        # drawable to the APK.
        ("tv_banner_lockup", "-lockup", " (lockup only)",
         banner_lockup_layers(), True, False),
    )
    for name, suffix, title_suffix, layers, alpha, in_apk in forms:
        w, h = int(BANNER_W * 2), int(BANNER_H * 2)
        buf = render(scale_layers(layers, w / BANNER_W), w, h)
        if in_apk:
            written.append(write(os.path.join(RES, "drawable-xhdpi", "%s.png" % name),
                                 png_bytes(buf, w, h, alpha=alpha)))
        written.append(write(os.path.join(BRAND, "kbstream-banner%s.png" % suffix),
                             png_bytes(buf, w, h, alpha=alpha)))
        written.append(write(
            os.path.join(BRAND, "kbstream-banner%s.svg" % suffix),
            svg_doc(layers, BANNER_W, BANNER_H, "KBStream TV banner" + title_suffix),
        ))
    return written


def emit_store_banners():
    """The store listing plates: the same plate, laid out at listing sizes."""
    written = []
    for name, w, h, k in STORE_PLATES:
        layers = plate_layers(w, h, k)
        iw, ih = int(w), int(h)
        written.append(write(os.path.join(BRAND, name + ".png"),
                             png_bytes(render(layers, iw, ih), iw, ih, alpha=False)))
        written.append(write(os.path.join(BRAND, name + ".svg"),
                             svg_doc(layers, w, h, name)))
    return written


def emit_icons():
    written = []
    for dens, px in ICON_SIZES:
        k = px / TILE
        for name, round_icon in (("ic_launcher", False), ("ic_launcher_round", True)):
            layers = scale_layers(icon_layers(round_icon), k)
            buf = render(layers, px, px, ss=SS)
            written.append(write(
                os.path.join(RES, "mipmap-%s" % dens, "%s.png" % name),
                png_bytes(buf, px, px, alpha=True),
            ))
    # 512 is the size the Play Console asks for, so it is written exactly rather
    # than resampled from the largest launcher bucket (192px).
    for name, px in (("kbstream-icon.png", 432), ("kbstream-icon-512.png", 512)):
        written.append(write(
            os.path.join(BRAND, name),
            png_bytes(render(scale_layers(icon_layers(), px / TILE), px, px), px, px),
        ))
    big = 432
    written.append(write(os.path.join(BRAND, "kbstream-icon.svg"),
                         svg_doc(icon_layers(), TILE, TILE, "KBStream app icon")))
    written.append(write(os.path.join(BRAND, "kbstream-icon-round.png"),
                         png_bytes(render(scale_layers(icon_layers(True), big / TILE), big, big), big, big)))
    return written


def emit_logo():
    layers = logo_layers()
    k = 2
    w, h = int(LOGO_W * k), int(LOGO_H * k)
    written = [write(os.path.join(BRAND, "kbstream-logo.png"),
                     png_bytes(render(scale_layers(layers, k), w, h), w, h))]
    written.append(write(os.path.join(BRAND, "kbstream-logo.svg"),
                         svg_doc(layers, LOGO_W, LOGO_H, "KBStream logo")))
    # mark alone, for favicons and anywhere the lockup is too wide
    d = 480.0
    written.append(write(os.path.join(BRAND, "kbstream-mark.svg"),
                         svg_doc(mark_layers(d, 0.0, 0.0), d, d, "KBStream mark")))
    written.append(write(os.path.join(BRAND, "kbstream-mark.png"),
                         png_bytes(render(mark_layers(d, 0.0, 0.0), int(d), int(d)), int(d), int(d))))
    return written


def emit_vectors():
    """The adaptive icon's layers, plus the monochrome (themed-icon) variant."""
    d = ICON_MARK_D
    ox = oy = (TILE - d) / 2.0
    glyph = _poly_d(mark(d, ox, oy))
    fg = [(glyph, lin((0.0, oy), (0.0, oy + d), BRASS_HI, BRASS_LO))]
    # The plate is full-bleed: the launcher applies the mask and the shadow ring.
    bg = [
        (_poly_d([rect(0, 0, TILE, TILE)]), lin((0, 0), (0, TILE), TILE_TOP, TILE_BOT)),
        (_poly_d([circle(TILE / 2.0, TILE / 2.0, 52.0)]),
         rad((TILE / 2.0, TILE / 2.0 - 4), 52.0, BRASS, 0.17)),
    ]
    mono = [(glyph, solid(rgb("FFFFFF")))]
    written = [
        write(os.path.join(RES, "drawable", "ic_launcher_background.xml"),
              vector_xml(TILE, TILE, TILE, bg,
                         "KBStream icon plate: the theme's void navy with the brass halo.")),
        write(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"),
              vector_xml(TILE, TILE, TILE, fg,
                         "KBStream mark: the brass play button. %.0f of the 108dp layer, so it\n"
                         "     sits inside the 66dp safe circle the launcher masks to." % ICON_MARK_D)),
        write(os.path.join(RES, "drawable", "ic_launcher_monochrome.xml"),
              vector_xml(TILE, TILE, TILE, mono,
                         "Single-colour mark for Android 13+ themed icons.")),
    ]
    anydpi = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@drawable/ic_launcher_background" />\n'
        '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
        '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
        '</adaptive-icon>\n'
    )
    written.append(write(os.path.join(RES, "mipmap-anydpi-v26", "ic_launcher.xml"), anydpi))
    written.append(write(os.path.join(RES, "mipmap-anydpi-v26", "ic_launcher_round.xml"), anydpi))
    return written


def emit_brand_play():
    """The brand mark alone as a vector drawable, for the detail screen's PLAY
    control: the ringed brass play button (the logo/icon mark) rather than the
    bare control-bar triangle.

    Emitted with its own brass gradients so the caller can draw it untinted;
    the glass face, the bezel and the glyph each keep their own fill, exactly
    as on the icon.
    """
    d = 32.0
    cx = cy = d / 2.0
    bezel, tri = mark_split(d, 0.0, 0.0)
    face = [circle(cx, cy, d / 2.0 * (1.0 - 2.0 * MARK_RING))]
    shapes = [
        (_poly_d(face), rad((cx, cy - 0.06 * d), 0.62 * d, BRASS, MARK_FACE)),
        (_poly_d(bezel), lin((0.0, 0.0), (0.0, d), BRASS, BRASS_LO)),
        (_poly_d(tri), lin((0.0, 0.0), (0.0, d), BRASS_HI, BRASS)),
    ]
    return [write(
        os.path.join(RES, "drawable", "ic_brand_play.xml"),
        vector_xml(24.0, d, d, shapes,
                   "KBStream mark: the ringed brass play button, used for the\n"
                   "     detail screen's PLAY control. Drawn with its own brass\n"
                   "     gradients so it renders untinted, like the logo. Generated\n"
                   "     by scripts/render_brand_assets.py."),
    )]


def emit_transparent_icon():
    """The app mark on a FULLY TRANSPARENT background -- no navy plate -- for a
    TV launcher that wants the bare lockup. Same mark, same 66dp safe-circle
    sizing as the icon, just nothing painted behind it. Docs-only: it is not a
    packaged drawable, it is a file to sideload.
    """
    written = []
    d = ICON_MARK_D
    layers = mark_layers(d, (TILE - d) / 2.0, (TILE - d) / 2.0)
    for name, px in (("kbstream-icon-transparent.png", 512),
                     ("kbstream-icon-transparent-256.png", 256)):
        buf = render(scale_layers(layers, px / TILE), px, px, ss=SS)
        written.append(write(os.path.join(BRAND, name),
                             png_bytes(buf, px, px, alpha=True)))
    return written


def emit_notification_icon():
    """The notification small icon. The system alpha-masks it and draws it at
    ~18dp, where a bezel thinner than a pixel and a glass face would both be
    lost, so this one is the bare glyph: bigger, solid, no ring."""
    d = 24.0
    tri_h = d * 0.80
    tri_w = tri_h * MARK_TRI_ASPECT
    tx = (d - tri_w) / 2.0 + d * 0.03
    ty = (d - tri_h) / 2.0
    tri = rounded_polygon(
        [(tx, ty), (tx + tri_w, d / 2.0), (tx, ty + tri_h)], MARK_FILLET * tri_h
    )
    return [write(os.path.join(RES, "drawable", "ic_notification.xml"),
                  vector_xml(d, d, d, [(_poly_d([tri]), solid(rgb("FFFFFF")))],
                             "KBStream notification glyph: the play mark alone, white\n"
                             "     because the system tints (alpha-masks) small icons."))]


def emit_sheet():
    """One image to review everything at once."""
    w, h = 760, 780
    buf = new_buffer(w, h)
    fill(buf, w, h, [rect(0, 0, w, h)], solid(rgb("222834")))
    bw, bh = 640, 360
    blit(buf, w, h, render(scale_layers(banner_layers(), bw / BANNER_W), bw, bh), bw, bh, 60, 40)
    x = 60
    for px in (144, 96, 72, 48):
        icon = render(scale_layers(icon_layers(), px / TILE), px, px)
        blit(buf, w, h, icon, px, px, x, 500 - px // 2)
        x += px + 30
    rnd = render(scale_layers(icon_layers(True), 144 / TILE), 144, 144)
    blit(buf, w, h, rnd, 144, 144, x, 428)
    logo = render(scale_layers(logo_layers(), 1.6), int(LOGO_W * 1.6), int(LOGO_H * 1.6))
    blit(buf, w, h, logo, int(LOGO_W * 1.6), int(LOGO_H * 1.6), 60, 600)
    return [write(os.path.join(BRAND, "preview.png"), png_bytes(buf, w, h))]


def emit_store_sheet():
    """The listing plates on their own sheet, so the launcher set stays one
    readable image instead of growing a row of very wide plates under it."""
    fg_w, fg_h = 1024, 500
    hd_scale = 0.9
    hd_w, hd_h = int(1280 * hd_scale), int(720 * hd_scale)
    pad, gap = 40, 30
    w = max(fg_w, hd_w) + 2 * pad
    h = pad + fg_h + gap + hd_h + pad
    buf = new_buffer(w, h)
    fill(buf, w, h, [rect(0, 0, w, h)], solid(rgb("222834")))
    fg = render(plate_layers(1024.0, 500.0, 3.2), fg_w, fg_h)
    blit(buf, w, h, fg, fg_w, fg_h, (w - fg_w) // 2, pad)
    hd = render(scale_layers(plate_layers(1280.0, 720.0, 4.0), hd_scale), hd_w, hd_h)
    blit(buf, w, h, hd, hd_w, hd_h, (w - hd_w) // 2, pad + fg_h + gap)
    return [write(os.path.join(BRAND, "preview-store.png"), png_bytes(buf, w, h))]


# --------------------------------------------------------------------------- #
# ASCII preview, for checking a design without an image viewer
# --------------------------------------------------------------------------- #

def ascii_preview(layers, w, h, cols=104):
    buf = render(layers, w, h, ss=2)
    ramp = " .:-=+*#%@"
    cell_w = w / cols
    rows = max(1, int(round(h / (cell_w * 2.05))))
    cell_h = h / rows
    lines = []
    for r in range(rows):
        line = []
        for c in range(cols):
            x0, x1 = int(c * cell_w), max(int(c * cell_w) + 1, int((c + 1) * cell_w))
            y0, y1 = int(r * cell_h), max(int(r * cell_h) + 1, int((r + 1) * cell_h))
            tot = 0.0
            n = 0
            for y in range(y0, min(y1, h), max(1, (y1 - y0) // 4)):
                for x in range(x0, min(x1, w), max(1, (x1 - x0) // 4)):
                    i = (y * w + x) * 4
                    lum = (0.2126 * buf[i] + 0.7152 * buf[i + 1] + 0.0722 * buf[i + 2]) * buf[i + 3]
                    tot += lum
                    n += 1
            v = tot / max(1, n)
            line.append(ramp[min(len(ramp) - 1, int(v * len(ramp) * 1.55))])
        lines.append("".join(line))
    return "\n".join(lines)


PREVIEWS = {
    "banner": lambda: (banner_layers(), int(BANNER_W), int(BANNER_H)),
    "plate": lambda: (banner_layers(solid=True), int(BANNER_W), int(BANNER_H)),
    "lockup": lambda: (banner_lockup_layers(), int(BANNER_W), int(BANNER_H)),
    "promo": lambda: (plate_layers(1024.0, 500.0, 3.2), 1024, 500),
    "icon": lambda: (icon_layers(), int(TILE), int(TILE)),
    "round": lambda: (icon_layers(True), int(TILE), int(TILE)),
    "logo": lambda: (logo_layers(), int(LOGO_W), int(LOGO_H)),
    "mark": lambda: (mark_layers(64.0, 0.0, 0.0), 64, 64),
}


def main():
    if len(sys.argv) > 2 and sys.argv[1] == "--preview":
        layers, w, h = PREVIEWS[sys.argv[2]]()
        print(ascii_preview(layers, w, h))
        return
    written = (
        emit_banner() + emit_store_banners() + emit_icons() + emit_logo()
        + emit_vectors() + emit_brand_play() + emit_transparent_icon()
        + emit_notification_icon() + emit_sheet()
        + emit_store_sheet()
    )
    for path in written:
        print(path)


if __name__ == "__main__":
    main()
